
# Load packages ------
if (!require("pacman")) install.packages("pacman")

pacman::p_load(readr, dplyr, ggplot2, scales, ggforce)


metabo = read_csv("/mnt/project/results/1_limma_analysis/2025_12_15_metabolites_associated_GDM.csv")

# metabo %>%  
#   dplyr::filter(adj.P.Val < 0.05) %>% 
#   nrow()


met_classes = list(
  Cholesterol = c("total_cholesterol", "total_cholesterol_minus_hdl_c", "remnant_cholesterol_non_hdl_non_ldl_cholesterol", 
                  "vldl_cholesterol",  "cholesterol_in_idl", "clinical_ldl_cholesterol", "ldl_cholesterol", "hdl_cholesterol",
                  "cholesterol_in_chylomicrons_and_extremely_large_vldl", "cholesterol_in_very_large_vldl", "cholesterol_in_large_vldl", "cholesterol_in_medium_vldl", "cholesterol_in_small_vldl", "cholesterol_in_very_small_vldl",
                  "cholesterol_in_large_ldl", "cholesterol_in_medium_ldl", "cholesterol_in_small_ldl",
                  "cholesterol_in_very_large_hdl",  "cholesterol_in_large_hdl", "cholesterol_in_medium_hdl", "cholesterol_in_small_hdl",
                  "cholesterol_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                  "cholesterol_to_total_lipids_in_very_large_vldl_percentage", "cholesterol_to_total_lipids_in_large_vldl_percentage", "cholesterol_to_total_lipids_in_medium_vldl_percentage", "cholesterol_to_total_lipids_in_small_vldl_percentage", "cholesterol_to_total_lipids_in_very_small_vldl_percentage", 
                  "cholesterol_to_total_lipids_in_idl_percentage", 
                  "cholesterol_to_total_lipids_in_large_ldl_percentage", "cholesterol_to_total_lipids_in_medium_ldl_percentage", "cholesterol_to_total_lipids_in_small_ldl_percentage",  
                  "cholesterol_to_total_lipids_in_very_large_hdl_percentage", "cholesterol_to_total_lipids_in_large_hdl_percentage", "cholesterol_to_total_lipids_in_medium_hdl_percentage", "cholesterol_to_total_lipids_in_small_hdl_percentage"),
  Triglycerides = c("total_triglycerides", 
                    "triglycerides_in_vldl", "triglycerides_in_idl", 
                    "triglycerides_in_ldl", "triglycerides_in_hdl", 
                    "triglycerides_in_chylomicrons_and_extremely_large_vldl", "triglycerides_in_very_large_vldl", "triglycerides_in_large_vldl", "triglycerides_in_medium_vldl", "triglycerides_in_small_vldl", "triglycerides_in_very_small_vldl", 
                    "triglycerides_in_large_ldl", "triglycerides_in_medium_ldl", "triglycerides_in_small_ldl", 
                    "triglycerides_in_very_large_hdl", "triglycerides_in_large_hdl",  "triglycerides_in_medium_hdl",  "triglycerides_in_small_hdl", 
                    "triglycerides_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                    "triglycerides_to_total_lipids_in_very_large_vldl_percentage", "triglycerides_to_total_lipids_in_large_vldl_percentage", "triglycerides_to_total_lipids_in_medium_vldl_percentage", "triglycerides_to_total_lipids_in_small_vldl_percentage", "triglycerides_to_total_lipids_in_very_small_vldl_percentage", 
                    "triglycerides_to_total_lipids_in_idl_percentage", 
                    "triglycerides_to_total_lipids_in_large_ldl_percentage", "triglycerides_to_total_lipids_in_medium_ldl_percentage", "triglycerides_to_total_lipids_in_small_ldl_percentage", 
                    "triglycerides_to_total_lipids_in_very_large_hdl_percentage", "triglycerides_to_total_lipids_in_large_hdl_percentage", "triglycerides_to_total_lipids_in_medium_hdl_percentage", "triglycerides_to_total_lipids_in_small_hdl_percentage"),
  Phospholipids = c("total_phospholipids_in_lipoprotein_particles", 
                    "phospholipids_in_vldl",  "phospholipids_in_idl", "phospholipids_in_ldl", "phospholipids_in_hdl", 
                    "phospholipids_in_chylomicrons_and_extremely_large_vldl", "phospholipids_in_very_large_vldl",  "phospholipids_in_large_vldl", "phospholipids_in_medium_vldl", "phospholipids_in_small_vldl", "phospholipids_in_very_small_vldl",
                    "phospholipids_in_large_ldl", "phospholipids_in_medium_ldl", "phospholipids_in_small_ldl",
                    "phospholipids_in_very_large_hdl", "phospholipids_in_large_hdl", "phospholipids_in_medium_hdl", "phospholipids_in_small_hdl", 
                    "phospholipids_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                    "phospholipids_to_total_lipids_in_very_large_vldl_percentage", "phospholipids_to_total_lipids_in_large_vldl_percentage", "phospholipids_to_total_lipids_in_medium_vldl_percentage", "phospholipids_to_total_lipids_in_small_vldl_percentage", "phospholipids_to_total_lipids_in_very_small_vldl_percentage", 
                    "phospholipids_to_total_lipids_in_idl_percentage", 
                    "phospholipids_to_total_lipids_in_large_ldl_percentage", "phospholipids_to_total_lipids_in_medium_ldl_percentage", "phospholipids_to_total_lipids_in_small_ldl_percentage", 
                    "phospholipids_to_total_lipids_in_very_large_hdl_percentage", "phospholipids_to_total_lipids_in_large_hdl_percentage", "phospholipids_to_total_lipids_in_medium_hdl_percentage", "phospholipids_to_total_lipids_in_small_hdl_percentage"),
  Cholesteryl_esters = c("total_esterified_cholesterol", 
                         "cholesteryl_esters_in_vldl", "cholesteryl_esters_in_idl", 
                         "cholesteryl_esters_in_ldl", "cholesteryl_esters_in_hdl", 
                         "cholesteryl_esters_in_chylomicrons_and_extremely_large_vldl",  "cholesteryl_esters_in_very_large_vldl", "cholesteryl_esters_in_large_vldl", "cholesteryl_esters_in_medium_vldl", "cholesteryl_esters_in_small_vldl", "cholesteryl_esters_in_very_small_vldl",
                         "cholesteryl_esters_in_large_ldl", "cholesteryl_esters_in_medium_ldl", "cholesteryl_esters_in_small_ldl",
                         "cholesteryl_esters_in_very_large_hdl", "cholesteryl_esters_in_large_hdl", "cholesteryl_esters_in_medium_hdl",   "cholesteryl_esters_in_small_hdl", 
                         "cholesteryl_esters_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                         "cholesteryl_esters_to_total_lipids_in_very_large_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_large_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_medium_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_small_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_very_small_vldl_percentage", 
                         "cholesteryl_esters_to_total_lipids_in_idl_percentage",
                         "cholesteryl_esters_to_total_lipids_in_large_ldl_percentage", "cholesteryl_esters_to_total_lipids_in_medium_ldl_percentage", "cholesteryl_esters_to_total_lipids_in_small_ldl_percentage",
                         "cholesteryl_esters_to_total_lipids_in_very_large_hdl_percentage", "cholesteryl_esters_to_total_lipids_in_large_hdl_percentage", "cholesteryl_esters_to_total_lipids_in_medium_hdl_percentage", "cholesteryl_esters_to_total_lipids_in_small_hdl_percentage"),
  Free_cholesterol = c("total_free_cholesterol",  
                       "free_cholesterol_in_vldl", "free_cholesterol_in_idl", 
                       "free_cholesterol_in_ldl", "free_cholesterol_in_hdl", 
                       "free_cholesterol_in_chylomicrons_and_extremely_large_vldl", "free_cholesterol_in_very_large_vldl", "free_cholesterol_in_large_vldl", "free_cholesterol_in_medium_vldl", "free_cholesterol_in_small_vldl", "free_cholesterol_in_very_small_vldl", 
                       "free_cholesterol_in_large_ldl", "free_cholesterol_in_medium_ldl", "free_cholesterol_in_small_ldl", 
                       "free_cholesterol_in_very_large_hdl", "free_cholesterol_in_large_hdl",  "free_cholesterol_in_medium_hdl",  "free_cholesterol_in_small_hdl", 
                       "free_cholesterol_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", "free_cholesterol_to_total_lipids_in_very_large_vldl_percentage", "free_cholesterol_to_total_lipids_in_large_vldl_percentage",
                       "free_cholesterol_to_total_lipids_in_medium_vldl_percentage", "free_cholesterol_to_total_lipids_in_small_vldl_percentage", "free_cholesterol_to_total_lipids_in_very_small_vldl_percentage", 
                       "free_cholesterol_to_total_lipids_in_idl_percentage", 
                       "free_cholesterol_to_total_lipids_in_large_ldl_percentage", "free_cholesterol_to_total_lipids_in_medium_ldl_percentage",  "free_cholesterol_to_total_lipids_in_small_ldl_percentage", 
                       "free_cholesterol_to_total_lipids_in_very_large_hdl_percentage", "free_cholesterol_to_total_lipids_in_large_hdl_percentage", "free_cholesterol_to_total_lipids_in_medium_hdl_percentage", "free_cholesterol_to_total_lipids_in_small_hdl_percentage" 
                       ),
  Total_lipids = c("total_lipids_in_lipoprotein_particles",  
                   "total_lipids_in_vldl", "total_lipids_in_idl", "total_lipids_in_ldl", "total_lipids_in_hdl",
                   "total_lipids_in_chylomicrons_and_extremely_large_vldl", "total_lipids_in_very_large_vldl",  "total_lipids_in_large_vldl", "total_lipids_in_medium_vldl", "total_lipids_in_small_vldl", "total_lipids_in_very_small_vldl", 
                    "total_lipids_in_large_ldl", "total_lipids_in_medium_ldl", "total_lipids_in_small_ldl",
                   "total_lipids_in_very_large_hdl", "total_lipids_in_large_hdl",  "total_lipids_in_medium_hdl", "total_lipids_in_small_hdl"),
  LP_concentration = c("total_concentration_of_lipoprotein_particles",  "concentration_of_chylomicrons_and_extremely_large_vldl_particles", "concentration_of_vldl_particles", "concentration_of_idl_particles",  "concentration_of_ldl_particles", "concentration_of_hdl_particles",
                       "concentration_of_very_large_vldl_particles", "concentration_of_large_vldl_particles",  "concentration_of_medium_vldl_particles", "concentration_of_small_vldl_particles", "concentration_of_very_small_vldl_particles", 
                       "concentration_of_large_ldl_particles", "concentration_of_medium_ldl_particles", "concentration_of_small_ldl_particles",
                       "concentration_of_very_large_hdl_particles", "concentration_of_large_hdl_particles", "concentration_of_medium_hdl_particles",  "concentration_of_small_hdl_particles"),
  Other_lipids = c("total_cholines", "phosphatidylcholines", "phosphoglycerides", "sphingomyelins", "triglycerides_to_phosphoglycerides_ratio"),
  ApoLP_size = c("apolipoprotein_b", "apolipoprotein_a1", "apolipoprotein_b_to_apolipoprotein_a1_ratio", "average_diameter_for_vldl_particles", "average_diameter_for_ldl_particles", "average_diameter_for_hdl_particles"),
  Fatty_acids = c("total_fatty_acids", "degree_of_unsaturation", "omega_3_fatty_acids", "omega_6_fatty_acids", "polyunsaturated_fatty_acids", "monounsaturated_fatty_acids", "saturated_fatty_acids", "linoleic_acid", "docosahexaenoic_acid", "omega_3_fatty_acids_to_total_fatty_acids_percentage", "omega_6_fatty_acids_to_total_fatty_acids_percentage", "omega_6_fatty_acids_to_omega_3_fatty_acids_ratio", "polyunsaturated_fatty_acids_to_total_fatty_acids_percentage", "monounsaturated_fatty_acids_to_total_fatty_acids_percentage", "saturated_fatty_acids_to_total_fatty_acids_percentage", "linoleic_acid_to_total_fatty_acids_percentage", "docosahexaenoic_acid_to_total_fatty_acids_percentage", "polyunsaturated_fatty_acids_to_monounsaturated_fatty_acids_ratio", "omega_6_fatty_acids_to_omega_3_fatty_acids_ratio"),
  Amino_acids = c("spectrometer_corrected_alanine", "alanine", "glutamine", "glycine", "histidine", "isoleucine", "leucine", "phenylalanine", "tyrosine", "valine", "total_concentration_of_branched_chain_amino_acids_leucine_isoleucine_valine"),
  Glycolysis = c("glucose", "lactate", "glucose_lactate", "pyruvate", "citrate"),
  Ketone_bodies = c( "acetate", "acetoacetate", "acetone", "x3_hydroxybutyrate"),
  Fluid_balance = c("creatinine", "albumin"),
  Inflammation = c("glycoprotein_acetyls")
)

metabo = metabo %>%
  dplyr::mutate(
    class = dplyr::case_when(
      Metabolite %in% met_classes$Cholesterol                           ~ "Cholesterol",
      Metabolite %in% met_classes$Triglycerides                         ~ "Triglycerides",
      Metabolite %in% met_classes$Phospholipids                         ~ "Phospholipids",
      Metabolite %in% met_classes$Cholesteryl_esters                    ~ "Cholesteryl_esters",
      Metabolite %in% met_classes$Free_cholesterol                      ~ "Free_cholesterol",
      Metabolite %in% met_classes$Total_lipids                          ~ "Total_lipids",
      Metabolite %in% met_classes$LP_concentration                      ~ "LP_concentration",
      Metabolite %in% met_classes$Other_lipids                          ~ "Other_lipids",
      Metabolite %in% met_classes$ApoLP_size                            ~ "ApoLP_size",
      Metabolite %in% met_classes$Fatty_acids                           ~ "Fatty_acids",
      Metabolite %in% met_classes$Amino_acids                           ~ "Amino_acids",
      Metabolite %in% met_classes$Glycolysis                            ~ "Glycolysis",
      Metabolite %in% met_classes$Ketone_bodies                         ~ "Ketone_bodies",
      Metabolite %in% met_classes$Fluid_balance                         ~ "Fluid_balance",
      Metabolite %in% met_classes$Inflammation                          ~ "Inflammation",
      TRUE                                                              ~ NA_character_))

metabo = metabo %>% 
  dplyr::arrange(class, Metabolite)

met_list = c("total_cholesterol", "total_cholesterol_minus_hdl_c", "remnant_cholesterol_non_hdl_non_ldl_cholesterol", 
             "vldl_cholesterol",  "cholesterol_in_idl", "clinical_ldl_cholesterol", "ldl_cholesterol", "hdl_cholesterol",
             "cholesterol_in_chylomicrons_and_extremely_large_vldl", "cholesterol_in_very_large_vldl", "cholesterol_in_large_vldl", "cholesterol_in_medium_vldl", "cholesterol_in_small_vldl", "cholesterol_in_very_small_vldl",
                  "cholesterol_in_large_ldl", "cholesterol_in_medium_ldl", "cholesterol_in_small_ldl",
                  "cholesterol_in_very_large_hdl",  "cholesterol_in_large_hdl", "cholesterol_in_medium_hdl", "cholesterol_in_small_hdl",
                  "cholesterol_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                  "cholesterol_to_total_lipids_in_very_large_vldl_percentage", "cholesterol_to_total_lipids_in_large_vldl_percentage", "cholesterol_to_total_lipids_in_medium_vldl_percentage", "cholesterol_to_total_lipids_in_small_vldl_percentage", "cholesterol_to_total_lipids_in_very_small_vldl_percentage", 
                  "cholesterol_to_total_lipids_in_idl_percentage", 
                  "cholesterol_to_total_lipids_in_large_ldl_percentage", "cholesterol_to_total_lipids_in_medium_ldl_percentage", "cholesterol_to_total_lipids_in_small_ldl_percentage",  
                  "cholesterol_to_total_lipids_in_very_large_hdl_percentage", "cholesterol_to_total_lipids_in_large_hdl_percentage", "cholesterol_to_total_lipids_in_medium_hdl_percentage", "cholesterol_to_total_lipids_in_small_hdl_percentage", 
             "total_triglycerides", 
                    "triglycerides_in_vldl", "triglycerides_in_idl", 
                    "triglycerides_in_ldl", "triglycerides_in_hdl", 
                    "triglycerides_in_chylomicrons_and_extremely_large_vldl", "triglycerides_in_very_large_vldl", "triglycerides_in_large_vldl", "triglycerides_in_medium_vldl", "triglycerides_in_small_vldl", "triglycerides_in_very_small_vldl", 
                    "triglycerides_in_large_ldl", "triglycerides_in_medium_ldl", "triglycerides_in_small_ldl", 
                    "triglycerides_in_very_large_hdl", "triglycerides_in_large_hdl",  "triglycerides_in_medium_hdl",  "triglycerides_in_small_hdl", 
                    "triglycerides_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                    "triglycerides_to_total_lipids_in_very_large_vldl_percentage", "triglycerides_to_total_lipids_in_large_vldl_percentage", "triglycerides_to_total_lipids_in_medium_vldl_percentage", "triglycerides_to_total_lipids_in_small_vldl_percentage", "triglycerides_to_total_lipids_in_very_small_vldl_percentage", 
                    "triglycerides_to_total_lipids_in_idl_percentage", 
                    "triglycerides_to_total_lipids_in_large_ldl_percentage", "triglycerides_to_total_lipids_in_medium_ldl_percentage", "triglycerides_to_total_lipids_in_small_ldl_percentage", 
                    "triglycerides_to_total_lipids_in_very_large_hdl_percentage", "triglycerides_to_total_lipids_in_large_hdl_percentage", "triglycerides_to_total_lipids_in_medium_hdl_percentage", "triglycerides_to_total_lipids_in_small_hdl_percentage",
  "total_phospholipids_in_lipoprotein_particles", 
                    "phospholipids_in_vldl",  "phospholipids_in_idl", "phospholipids_in_ldl", "phospholipids_in_hdl", 
                    "phospholipids_in_chylomicrons_and_extremely_large_vldl", "phospholipids_in_very_large_vldl",  "phospholipids_in_large_vldl", "phospholipids_in_medium_vldl", "phospholipids_in_small_vldl", "phospholipids_in_very_small_vldl",
                    "phospholipids_in_large_ldl", "phospholipids_in_medium_ldl", "phospholipids_in_small_ldl",
                    "phospholipids_in_very_large_hdl", "phospholipids_in_large_hdl", "phospholipids_in_medium_hdl", "phospholipids_in_small_hdl", 
                    "phospholipids_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                    "phospholipids_to_total_lipids_in_very_large_vldl_percentage", "phospholipids_to_total_lipids_in_large_vldl_percentage", "phospholipids_to_total_lipids_in_medium_vldl_percentage", "phospholipids_to_total_lipids_in_small_vldl_percentage", "phospholipids_to_total_lipids_in_very_small_vldl_percentage", 
                    "phospholipids_to_total_lipids_in_idl_percentage", 
                    "phospholipids_to_total_lipids_in_large_ldl_percentage", "phospholipids_to_total_lipids_in_medium_ldl_percentage", "phospholipids_to_total_lipids_in_small_ldl_percentage", 
                    "phospholipids_to_total_lipids_in_very_large_hdl_percentage", "phospholipids_to_total_lipids_in_large_hdl_percentage", "phospholipids_to_total_lipids_in_medium_hdl_percentage", "phospholipids_to_total_lipids_in_small_hdl_percentage",
 "total_esterified_cholesterol", 
                         "cholesteryl_esters_in_vldl", "cholesteryl_esters_in_idl", 
                         "cholesteryl_esters_in_ldl", "cholesteryl_esters_in_hdl", 
                         "cholesteryl_esters_in_chylomicrons_and_extremely_large_vldl",  "cholesteryl_esters_in_very_large_vldl", "cholesteryl_esters_in_large_vldl", "cholesteryl_esters_in_medium_vldl", "cholesteryl_esters_in_small_vldl", "cholesteryl_esters_in_very_small_vldl",
                         "cholesteryl_esters_in_large_ldl", "cholesteryl_esters_in_medium_ldl", "cholesteryl_esters_in_small_ldl",
                         "cholesteryl_esters_in_very_large_hdl", "cholesteryl_esters_in_large_hdl", "cholesteryl_esters_in_medium_hdl",   "cholesteryl_esters_in_small_hdl", 
                         "cholesteryl_esters_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                         "cholesteryl_esters_to_total_lipids_in_very_large_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_large_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_medium_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_small_vldl_percentage", "cholesteryl_esters_to_total_lipids_in_very_small_vldl_percentage", 
                         "cholesteryl_esters_to_total_lipids_in_idl_percentage",
                         "cholesteryl_esters_to_total_lipids_in_large_ldl_percentage", "cholesteryl_esters_to_total_lipids_in_medium_ldl_percentage", "cholesteryl_esters_to_total_lipids_in_small_ldl_percentage",
                         "cholesteryl_esters_to_total_lipids_in_very_large_hdl_percentage", "cholesteryl_esters_to_total_lipids_in_large_hdl_percentage", "cholesteryl_esters_to_total_lipids_in_medium_hdl_percentage", "cholesteryl_esters_to_total_lipids_in_small_hdl_percentage",
  "total_free_cholesterol",  
                       "free_cholesterol_in_vldl", "free_cholesterol_in_idl", 
                       "free_cholesterol_in_ldl", "free_cholesterol_in_hdl", 
                       "free_cholesterol_in_chylomicrons_and_extremely_large_vldl", "free_cholesterol_in_very_large_vldl", "free_cholesterol_in_large_vldl", "free_cholesterol_in_medium_vldl", "free_cholesterol_in_small_vldl", "free_cholesterol_in_very_small_vldl", 
                       "free_cholesterol_in_large_ldl", "free_cholesterol_in_medium_ldl", "free_cholesterol_in_small_ldl", 
                       "free_cholesterol_in_very_large_hdl", "free_cholesterol_in_large_hdl",  "free_cholesterol_in_medium_hdl",  "free_cholesterol_in_small_hdl", 
                       "free_cholesterol_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", "free_cholesterol_to_total_lipids_in_very_large_vldl_percentage", "free_cholesterol_to_total_lipids_in_large_vldl_percentage",
                       "free_cholesterol_to_total_lipids_in_medium_vldl_percentage", "free_cholesterol_to_total_lipids_in_small_vldl_percentage", "free_cholesterol_to_total_lipids_in_very_small_vldl_percentage", 
                       "free_cholesterol_to_total_lipids_in_idl_percentage", 
                       "free_cholesterol_to_total_lipids_in_large_ldl_percentage", "free_cholesterol_to_total_lipids_in_medium_ldl_percentage",  "free_cholesterol_to_total_lipids_in_small_ldl_percentage", 
                       "free_cholesterol_to_total_lipids_in_very_large_hdl_percentage", "free_cholesterol_to_total_lipids_in_large_hdl_percentage", "free_cholesterol_to_total_lipids_in_medium_hdl_percentage", "free_cholesterol_to_total_lipids_in_small_hdl_percentage",
  "total_lipids_in_lipoprotein_particles",  
                   "total_lipids_in_vldl", "total_lipids_in_idl", "total_lipids_in_ldl", "total_lipids_in_hdl",
                   "total_lipids_in_chylomicrons_and_extremely_large_vldl", "total_lipids_in_very_large_vldl",  "total_lipids_in_large_vldl", "total_lipids_in_medium_vldl", "total_lipids_in_small_vldl", "total_lipids_in_very_small_vldl", 
                   "total_lipids_in_large_ldl", "total_lipids_in_medium_ldl", "total_lipids_in_small_ldl",
                   "total_lipids_in_very_large_hdl", "total_lipids_in_large_hdl",  "total_lipids_in_medium_hdl", "total_lipids_in_small_hdl",
  "total_concentration_of_lipoprotein_particles",  "concentration_of_chylomicrons_and_extremely_large_vldl_particles", "concentration_of_vldl_particles", "concentration_of_idl_particles",  "concentration_of_ldl_particles", "concentration_of_hdl_particles",
                       "concentration_of_very_large_vldl_particles", "concentration_of_large_vldl_particles",  "concentration_of_medium_vldl_particles", "concentration_of_small_vldl_particles", "concentration_of_very_small_vldl_particles", 
                       "concentration_of_large_ldl_particles", "concentration_of_medium_ldl_particles", "concentration_of_small_ldl_particles",
                       "concentration_of_very_large_hdl_particles", "concentration_of_large_hdl_particles", "concentration_of_medium_hdl_particles",  "concentration_of_small_hdl_particles",
  "total_cholines", "phosphatidylcholines", "phosphoglycerides", "sphingomyelins", "triglycerides_to_phosphoglycerides_ratio",
  "apolipoprotein_b", "apolipoprotein_a1", "apolipoprotein_b_to_apolipoprotein_a1_ratio", "average_diameter_for_vldl_particles", "average_diameter_for_ldl_particles", "average_diameter_for_hdl_particles",
  "total_fatty_acids", "degree_of_unsaturation", "omega_3_fatty_acids", "omega_6_fatty_acids", "polyunsaturated_fatty_acids", "monounsaturated_fatty_acids", "saturated_fatty_acids", "linoleic_acid", "docosahexaenoic_acid", "omega_3_fatty_acids_to_total_fatty_acids_percentage", "omega_6_fatty_acids_to_total_fatty_acids_percentage", "omega_6_fatty_acids_to_omega_3_fatty_acids_ratio", "polyunsaturated_fatty_acids_to_total_fatty_acids_percentage", "monounsaturated_fatty_acids_to_total_fatty_acids_percentage", "saturated_fatty_acids_to_total_fatty_acids_percentage", "linoleic_acid_to_total_fatty_acids_percentage", "docosahexaenoic_acid_to_total_fatty_acids_percentage", "polyunsaturated_fatty_acids_to_monounsaturated_fatty_acids_ratio",
 "spectrometer_corrected_alanine", "alanine", "glutamine", "glycine", "histidine", "isoleucine", "leucine", "phenylalanine", "tyrosine", "valine", "total_concentration_of_branched_chain_amino_acids_leucine_isoleucine_valine",
  "glucose", "lactate", "glucose_lactate", "pyruvate", "citrate",
   "acetate", "acetoacetate", "acetone", "x3_hydroxybutyrate",
 "creatinine", "albumin",
  "glycoprotein_acetyls"
)


# Guardar la lista completa como un archivo .R para su descarga


new_met_list = c("Total_CHOL" = "total_cholesterol", "Total_noHDL_CHOL" = "total_cholesterol_minus_hdl_c", 
                 "Remnant_CHOL" = "remnant_cholesterol_non_hdl_non_ldl_cholesterol", 
                 "VLDL_CHOL" = "vldl_cholesterol",
                 "IDL_CHOL" = "cholesterol_in_idl", 
                 "clinLDL_CHOL" = "clinical_ldl_cholesterol", 
                 "LDL_CHOL" = "ldl_cholesterol", 
                 "HDL_CHOL" = "hdl_cholesterol",
                 "XXL_VLDL_CHOL" = "cholesterol_in_chylomicrons_and_extremely_large_vldl", 
                 "XL_VLDL_CHOL" = "cholesterol_in_very_large_vldl", 
                 "L_VDLD_CHOL" = "cholesterol_in_large_vldl", 
                 "M_VLDL_CHOL" = "cholesterol_in_medium_vldl", 
                 "S_VLDL_CHOL" = "cholesterol_in_small_vldl", 
                 "XS_VLDL_CHOL" = "cholesterol_in_very_small_vldl",
                 "L_LDL_CHOL" = "cholesterol_in_large_ldl", 
                 "M_LDL_CHOL" = "cholesterol_in_medium_ldl", 
                 "S_LDL_CHOL" = "cholesterol_in_small_ldl",
                 "XL_HDL_CHOL" = "cholesterol_in_very_large_hdl",  
                 "L_HDL_CHOL" = "cholesterol_in_large_hdl", 
                 "M_HDL_CHOL" = "cholesterol_in_medium_hdl", 
                 "S_HDL_CHOL" = "cholesterol_in_small_hdl",
                 "CHOL_%_XXL_VLDL" = "cholesterol_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                 "CHOL_%_XL_VLDL" = "cholesterol_to_total_lipids_in_very_large_vldl_percentage", 
                 "CHOL_%_L_VLDL" = "cholesterol_to_total_lipids_in_large_vldl_percentage", 
                 "CHOL_%_M_VLDL" = "cholesterol_to_total_lipids_in_medium_vldl_percentage", 
                 "CHOL_%_S_VLDL" = "cholesterol_to_total_lipids_in_small_vldl_percentage", 
                 "CHOL_%_XS_VLDL" = "cholesterol_to_total_lipids_in_very_small_vldl_percentage", 
                 "CHOL_%_IDL" = "cholesterol_to_total_lipids_in_idl_percentage", 
                 "CHOL_%_L_LDL" = "cholesterol_to_total_lipids_in_large_ldl_percentage", 
                 "CHOL_%_M_LDL" = "cholesterol_to_total_lipids_in_medium_ldl_percentage", 
                 "CHOL_%_S_LDL" = "cholesterol_to_total_lipids_in_small_ldl_percentage",  
                 "CHOL_%_XL_HDL" = "cholesterol_to_total_lipids_in_very_large_hdl_percentage", 
                 "CHOL_%_L_HDL" = "cholesterol_to_total_lipids_in_large_hdl_percentage", 
                 "CHOL_%_M_HDL" = "cholesterol_to_total_lipids_in_medium_hdl_percentage", 
                 "CHOL_%_S_HDL" = "cholesterol_to_total_lipids_in_small_hdl_percentage",
                 "Total_TAG" = "total_triglycerides", 
                 "VLDL_TAG" = "triglycerides_in_vldl", 
                 "IDL_TAG" = "triglycerides_in_idl", 
                 "LDL_TAG" = "triglycerides_in_ldl", 
                 "HDL_TAG" = "triglycerides_in_hdl", 
                 "XXL_VLDL_TAG" = "triglycerides_in_chylomicrons_and_extremely_large_vldl", 
                 "XL_VLDL_TAG" = "triglycerides_in_very_large_vldl", 
                 "L_VLDL_TAG" = "triglycerides_in_large_vldl", 
                 "M_VLDL_TAG" = "triglycerides_in_medium_vldl", 
                 "S_VLDL_TAG" = "triglycerides_in_small_vldl", 
                 "XS_VLDL_TAG" = "triglycerides_in_very_small_vldl", 
                 "L_LDL_TAG" = "triglycerides_in_large_ldl", 
                 "M_LDL_TAG" = "triglycerides_in_medium_ldl", 
                 "S_LDL_TAG" = "triglycerides_in_small_ldl", 
                 "XL_HDL_TAG" = "triglycerides_in_very_large_hdl", 
                 "L_HDL_TAG" = "triglycerides_in_large_hdl",  
                 "M_HDL_TAG" = "triglycerides_in_medium_hdl",  
                 "S_HDL_TAG" = "triglycerides_in_small_hdl",
                 "TAG_%_XXL_VLDL" = "triglycerides_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                 "TAG_%_XL_VLDL" = "triglycerides_to_total_lipids_in_very_large_vldl_percentage", 
                 "TAG_%_L_VLDL" = "triglycerides_to_total_lipids_in_large_vldl_percentage", 
                 "TAG_%_M_VLDL" = "triglycerides_to_total_lipids_in_medium_vldl_percentage", 
                 "TAG_%_S_VLDL" = "triglycerides_to_total_lipids_in_small_vldl_percentage", 
                 "TAG_%_XS_VLDL" = "triglycerides_to_total_lipids_in_very_small_vldl_percentage", 
                 "TAG_%_IDL" = "triglycerides_to_total_lipids_in_idl_percentage", 
                 "TAG_%_L_LDL" = "triglycerides_to_total_lipids_in_large_ldl_percentage", 
                 "TAG_%_M_LDL" = "triglycerides_to_total_lipids_in_medium_ldl_percentage", 
                 "TAG_%_S_LDL" = "triglycerides_to_total_lipids_in_small_ldl_percentage", 
                 "TAG_%_XL_HDL" = "triglycerides_to_total_lipids_in_very_large_hdl_percentage", 
                 "TAG_%_L_HDL" = "triglycerides_to_total_lipids_in_large_hdl_percentage", 
                 "TAG_%_M_HDL" = "triglycerides_to_total_lipids_in_medium_hdl_percentage", 
                 "TAG_%_S_HDL" = "triglycerides_to_total_lipids_in_small_hdl_percentage",
                 "Total_PL" = "total_phospholipids_in_lipoprotein_particles", 
                 "VLDL_PL" = "phospholipids_in_vldl",  
                 "IDL_PL" = "phospholipids_in_idl", 
                 "LDL_PL" = "phospholipids_in_ldl", 
                 "HDL_PL" = "phospholipids_in_hdl", 
                 "XXL_VLDL_PL" = "phospholipids_in_chylomicrons_and_extremely_large_vldl", 
                 "XL_VLDL_PL" = "phospholipids_in_very_large_vldl",  
                 "L_VLDL_PL" = "phospholipids_in_large_vldl", 
                 "M_VLDL_PL" = "phospholipids_in_medium_vldl", 
                 "S_VLDL_PL" = "phospholipids_in_small_vldl", 
                 "XS_VLDL_PL" = "phospholipids_in_very_small_vldl",
                 "L_LDL_PL" = "phospholipids_in_large_ldl", 
                 "M_LDL_PL" = "phospholipids_in_medium_ldl", 
                 "S_LDL_PL" = "phospholipids_in_small_ldl",
                 "XL_HDL_PL" = "phospholipids_in_very_large_hdl", 
                 "L_HDL_PL" = "phospholipids_in_large_hdl", 
                 "M_HDL_PL" = "phospholipids_in_medium_hdl", 
                 "S_HDL_PL" = "phospholipids_in_small_hdl", 
                 "PL_%_XXL_VLDL" = "phospholipids_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                 "PL_%_XL_VLDL" = "phospholipids_to_total_lipids_in_very_large_vldl_percentage", 
                 "PL_%_L_VLDL" = "phospholipids_to_total_lipids_in_large_vldl_percentage", 
                 "PL_%_M_VLDL" = "phospholipids_to_total_lipids_in_medium_vldl_percentage", 
                 "PL_%_S_VLDL" = "phospholipids_to_total_lipids_in_small_vldl_percentage", 
                 "PL_%_XS_VLDL" = "phospholipids_to_total_lipids_in_very_small_vldl_percentage", 
                 "PL_%_IDL" = "phospholipids_to_total_lipids_in_idl_percentage", 
                 "PL_%_L_LDL" = "phospholipids_to_total_lipids_in_large_ldl_percentage", 
                 "PL_%_M_LDL" = "phospholipids_to_total_lipids_in_medium_ldl_percentage", 
                 "PL_%_S_LDL" = "phospholipids_to_total_lipids_in_small_ldl_percentage", 
                 "PL_%_XL_HDL" = "phospholipids_to_total_lipids_in_very_large_hdl_percentage", 
                 "PL_%_L_HDL" = "phospholipids_to_total_lipids_in_large_hdl_percentage", 
                 "PL_%_M_HDL" = "phospholipids_to_total_lipids_in_medium_hdl_percentage", 
                 "PL_%_S_HDL" = "phospholipids_to_total_lipids_in_small_hdl_percentage",
                 "Total_CHOLest" = "total_esterified_cholesterol", 
                 "VLDL_CHOLest" = "cholesteryl_esters_in_vldl", 
                 "IDL_CHOLest" = "cholesteryl_esters_in_idl", 
                 "LDL_CHOLest" = "cholesteryl_esters_in_ldl", 
                 "HDL_CHOLest" = "cholesteryl_esters_in_hdl", 
                 "XXL_VLDL_CHOLest" = "cholesteryl_esters_in_chylomicrons_and_extremely_large_vldl",  
                 "XL_VLDL_CHOLest" = "cholesteryl_esters_in_very_large_vldl", 
                 "L_VLDL_CHOLest" = "cholesteryl_esters_in_large_vldl", 
                 "M_VLDL_CHOLest" = "cholesteryl_esters_in_medium_vldl", 
                 "S_VLDL_CHOLest" = "cholesteryl_esters_in_small_vldl", 
                 "XS_VLDL_CHOLest" = "cholesteryl_esters_in_very_small_vldl",
                 "L_LDL_CHOLest" = "cholesteryl_esters_in_large_ldl", 
                 "M_LDL_CHOLest" = "cholesteryl_esters_in_medium_ldl", 
                 "S_LDL_CHOLest" = "cholesteryl_esters_in_small_ldl",
                 "XL_HDL_CHOLest" = "cholesteryl_esters_in_very_large_hdl", 
                 "L_HDL_CHOLest" = "cholesteryl_esters_in_large_hdl", 
                 "M_HDL_CHOLest" = "cholesteryl_esters_in_medium_hdl",   
                 "S_HDL_CHOLest" = "cholesteryl_esters_in_small_hdl",
                 "CHOLest_%_XXL_VLDL" = "cholesteryl_esters_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                 "CHOLest_%_XL_VLDL" = "cholesteryl_esters_to_total_lipids_in_very_large_vldl_percentage", 
                 "CHOLest_%_L_VLDL" = "cholesteryl_esters_to_total_lipids_in_large_vldl_percentage", 
                 "CHOLest_%_M_VLDL" = "cholesteryl_esters_to_total_lipids_in_medium_vldl_percentage", 
                 "CHOLest_%_S_VLDL" = "cholesteryl_esters_to_total_lipids_in_small_vldl_percentage", 
                 "CHOLest_%_XS_VLDL" = "cholesteryl_esters_to_total_lipids_in_very_small_vldl_percentage", 
                 "CHOLest_%_IDL" = "cholesteryl_esters_to_total_lipids_in_idl_percentage",
                 "CHOLest_%_L_LDL" = "cholesteryl_esters_to_total_lipids_in_large_ldl_percentage", 
                 "CHOLest_%_M_LDL" = "cholesteryl_esters_to_total_lipids_in_medium_ldl_percentage", 
                 "CHOLest_%_S_LDL" = "cholesteryl_esters_to_total_lipids_in_small_ldl_percentage",
                 "CHOLest_%_XL_HDL" = "cholesteryl_esters_to_total_lipids_in_very_large_hdl_percentage", 
                 "CHOLest_%_L_HDL" = "cholesteryl_esters_to_total_lipids_in_large_hdl_percentage", 
                 "CHOLest_%_M_HDL" = "cholesteryl_esters_to_total_lipids_in_medium_hdl_percentage", 
                 "CHOLest_%_S_HDL" = "cholesteryl_esters_to_total_lipids_in_small_hdl_percentage",
                 "Total_fCHOL" = "total_free_cholesterol",  
                 "VLDL_fCHOL" = "free_cholesterol_in_vldl", 
                 "IDL_fCHOL" = "free_cholesterol_in_idl", 
                 "LDL_fCHOL" = "free_cholesterol_in_ldl", 
                 "HDL_fCHOL" = "free_cholesterol_in_hdl", 
                 "XXL_VLDL_fCHOL" = "free_cholesterol_in_chylomicrons_and_extremely_large_vldl", 
                 "XL_VLDL_fCHOL" = "free_cholesterol_in_very_large_vldl", 
                 "L_VLDL_fCHOL" = "free_cholesterol_in_large_vldl", 
                 "M_VLDL_fCHOL" = "free_cholesterol_in_medium_vldl", 
                 "S_VLDL_fCHOL" = "free_cholesterol_in_small_vldl", 
                 "XS_VLDL_fCHOL" = "free_cholesterol_in_very_small_vldl", 
                 "L_LDL_fCHOL" = "free_cholesterol_in_large_ldl", 
                 "M_LDL_fCHOL" = "free_cholesterol_in_medium_ldl", 
                 "S_LDL_fCHOL" = "free_cholesterol_in_small_ldl", 
                 "XL_HDL_fCHOL" = "free_cholesterol_in_very_large_hdl", 
                 "L_HDL_fCHOL" = "free_cholesterol_in_large_hdl",  
                 "M_HDL_fCHOL" = "free_cholesterol_in_medium_hdl",  
                 "S_HDL_fCHOL" = "free_cholesterol_in_small_hdl",
                 "fCHOL_%_XXL_VLDL" = "free_cholesterol_to_total_lipids_in_chylomicrons_and_extremely_large_vldl_percentage", 
                 "fCHOL_%_XL_VLDL" = "free_cholesterol_to_total_lipids_in_very_large_vldl_percentage", 
                 "fCHOL_%_L_VLDL" = "free_cholesterol_to_total_lipids_in_large_vldl_percentage",
                 "fCHOL_%_M_VLDL" = "free_cholesterol_to_total_lipids_in_medium_vldl_percentage", 
                 "fCHOL_%_S_VLDL" = "free_cholesterol_to_total_lipids_in_small_vldl_percentage", 
                 "fCHOL_%_XS_VLDL" = "free_cholesterol_to_total_lipids_in_very_small_vldl_percentage", 
                 "fCHOL_%_IDL" = "free_cholesterol_to_total_lipids_in_idl_percentage", 
                 "fCHOL_%_L_LDL" = "free_cholesterol_to_total_lipids_in_large_ldl_percentage", 
                 "fCHOL_%_M_LDL" = "free_cholesterol_to_total_lipids_in_medium_ldl_percentage",  
                 "fCHOL_%_S_LDL" = "free_cholesterol_to_total_lipids_in_small_ldl_percentage", 
                 "fCHOL_%_XL_HDL" = "free_cholesterol_to_total_lipids_in_very_large_hdl_percentage", 
                 "fCHOL_%_L_HDL" = "free_cholesterol_to_total_lipids_in_large_hdl_percentage", 
                 "fCHOL_%_M_HDL" = "free_cholesterol_to_total_lipids_in_medium_hdl_percentage", 
                 "fCHOL_%_S_HDL" = "free_cholesterol_to_total_lipids_in_small_hdl_percentage",
                 "Totlip" = "total_lipids_in_lipoprotein_particles",  
                 "VLDL_totlip" = "total_lipids_in_vldl", 
                 "IDL_totlip" = "total_lipids_in_idl", 
                 "LDL_totlip" = "total_lipids_in_ldl", 
                 "HDL_totlip" = "total_lipids_in_hdl",
                 "XXL_VLDL_totlip" = "total_lipids_in_chylomicrons_and_extremely_large_vldl", 
                 "XL_VLDL_totlip" = "total_lipids_in_very_large_vldl",  
                 "L_VLDL_totlip" = "total_lipids_in_large_vldl", 
                 "M_VLDL_totlip" = "total_lipids_in_medium_vldl", 
                 "S_VLDL_totlip" = "total_lipids_in_small_vldl", 
                 "XS_VLDL_totlip" = "total_lipids_in_very_small_vldl", 
                 "L_LDL_totlip" = "total_lipids_in_large_ldl", 
                 "M_LDL_totlip" = "total_lipids_in_medium_ldl", 
                 "S_LDL_totlip" = "total_lipids_in_small_ldl",
                 "XL_HDL_totlip" = "total_lipids_in_very_large_hdl", 
                 "L_HDL_totlip" = "total_lipids_in_large_hdl",  
                 "M_HDL_totlip" = "total_lipids_in_medium_hdl", 
                 "S_HDL_totlip" = "total_lipids_in_small_hdl",
                 "Total_lipoprot" = "total_concentration_of_lipoprotein_particles",  
                 "VLDL" = "concentration_of_vldl_particles", 
                 "IDL" = "concentration_of_idl_particles",  
                 "LDL" = "concentration_of_ldl_particles", 
                 "HDL" = "concentration_of_hdl_particles",
                 "XXL_VLDL" = "concentration_of_chylomicrons_and_extremely_large_vldl_particles", 
                 "XL_VLDL" = "concentration_of_very_large_vldl_particles", 
                 "L_VLDL" = "concentration_of_large_vldl_particles",  
                 "M_VLDL" = "concentration_of_medium_vldl_particles", 
                 "S_VLDL" = "concentration_of_small_vldl_particles", 
                 "XS_VLDL" = "concentration_of_very_small_vldl_particles", 
                 "L_LDL" = "concentration_of_large_ldl_particles", 
                 "M_LDL" = "concentration_of_medium_ldl_particles", 
                 "S_LDL" = "concentration_of_small_ldl_particles",
                 "XL_HDL" = "concentration_of_very_large_hdl_particles", 
                 "L_HDL" = "concentration_of_large_hdl_particles", 
                 "M_HDL" = "concentration_of_medium_hdl_particles",  
                 "S_HDL" = "concentration_of_small_hdl_particles", 
                 "Cholines" = "total_cholines", 
                 "PC" = "phosphatidylcholines", 
                 "PG" = "phosphoglycerides", 
                 "SM" = "sphingomyelins", 
                 "TAG_PG_ratio" = "triglycerides_to_phosphoglycerides_ratio",
                 "Apob" = "apolipoprotein_b", 
                 "Apoa" = "apolipoprotein_a1", 
                 "Apob_apoa_ratio" = "apolipoprotein_b_to_apolipoprotein_a1_ratio", 
                 "VLDL_dia" = "average_diameter_for_vldl_particles", 
                 "LDL_dia" = "average_diameter_for_ldl_particles", 
                 "HDL_dia" = "average_diameter_for_hdl_particles",
                 "Total_FAs" = "total_fatty_acids", 
                 "Degree_unsaturation" = "degree_of_unsaturation", 
                 "Omega3" = "omega_3_fatty_acids", 
                 "Omega6" = "omega_6_fatty_acids", 
                 "PUFAs" = "polyunsaturated_fatty_acids", 
                 "MUFAs" = "monounsaturated_fatty_acids", 
                 "SFAs" = "saturated_fatty_acids", 
                 "LA" = "linoleic_acid", 
                 "DHA" = "docosahexaenoic_acid", 
                 "Omega3_per" = "omega_3_fatty_acids_to_total_fatty_acids_percentage", 
                 "Omega6_per" = "omega_6_fatty_acids_to_total_fatty_acids_percentage",
                 "PUFAs_per" = "polyunsaturated_fatty_acids_to_total_fatty_acids_percentage", 
                 "MUFAs_per" = "monounsaturated_fatty_acids_to_total_fatty_acids_percentage", 
                 "SFAs_per" = "saturated_fatty_acids_to_total_fatty_acids_percentage", 
                 "LA_per" = "linoleic_acid_to_total_fatty_acids_percentage", 
                 "DHA_per" = "docosahexaenoic_acid_to_total_fatty_acids_percentage", 
                 "Omega6_3_ratio" = "omega_6_fatty_acids_to_omega_3_fatty_acids_ratio", 
                 "PUFAs_MUFAs_ratio" = "polyunsaturated_fatty_acids_to_monounsaturated_fatty_acids_ratio",
                 "Alanine_corrected" = "spectrometer_corrected_alanine",
                 "Alanine" = "alanine", 
                 "Glutamine" = "glutamine", 
                 "Glycine" = "glycine", 
                 "Histidine" = "histidine", 
                 "Isoleucine" = "isoleucine", 
                 "Leucine" = "leucine", 
                 "Phenilalanine" = "phenylalanine", 
                 "Tyrosine" = "tyrosine", 
                 "Valine" = "valine", 
                 "BCAAs" = "total_concentration_of_branched_chain_amino_acids_leucine_isoleucine_valine",
                 "Glucose" = "glucose", 
                 "Lactate" = "lactate",
                 "Glucose-lactate" = "glucose_lactate",
                 "Pyruvate" = "pyruvate", 
                 "Citrate" = "citrate",
                 "Acetate" = "acetate", 
                 "Acetoacetate" = "acetoacetate", 
                 "Acetone" = "acetone", 
                 "3-Hydroxybutyrate" = "x3_hydroxybutyrate",
                 "Creatinine" = "creatinine", 
                 "Albumin" = "albumin",
                 "GlycA" = "glycoprotein_acetyls"
)



# Asegúrate de que new_met_list esté definido con comillas en ambos lados
# Ejemplo: "GlycA" = "glycoprotein_acetyls"

# Invertimos el vector para mapear desde valores a nombres
lookup <- setNames(names(new_met_list), new_met_list)

metabo$Metabolite <- lookup[metabo$Metabolite]

metabo2 = metabo %>% 
  dplyr::filter(metabo$adj.P.Val < 0.05)

metabo2$class %>% table(useNA = "ifany")

metabo2$`Chemical class` = factor(metabo2$class, 
    levels = c("Amino_acids", "Glycolysis", "Inflammation", 
               "Fatty_acids", "Other_lipids", 
               "LP_concentration", "ApoLP_size", "Total_lipids", 
               "Triglycerides", "Cholesterol", "Free_cholesterol", 
               "Cholesteryl_esters", "Phospholipids", "Fluid_balance", 
               "Ketone_bodies"
               ))

metabo2 = metabo2 %>%
  dplyr::arrange(`Chemical class`)  %>% 
  mutate(id = row_number(), 
         # angle = 90 - 360 * (id - 0.5) / n(),
         # hjust = ifelse(angle < -90, 1, 0),
         # angle = ifelse(angle < -90, angle + 180, angle),
         label_y = ifelse(logFC > 0, logFC + 0.01, 0.01),
         # vjust = ifelse(logFC > 0, 0, 1)
         )


cls = levels(metabo2$`Chemical class`)
pal = setNames(scales::hue_pal()(length(cls)), cls)

pal["Fluid_balance"]  = "#D16B86"
pal["Ketone_bodies"]  = "#B04A64"
    
  
    

# Crear el gráfico circular
ggplot(metabo2, aes(x = as.factor(id), y = logFC, fill = `Chemical class`)) +
  geom_bar(stat = "identity") +
  coord_radial(start = 0, end = -0.04 * pi,  expand = TRUE,
               inner.radius = 0.55, rotate_angle = TRUE) +
  geom_text(
    aes(
      y = label_y,
      label = Metabolite,
      angle = 90,
      hjust = 0,
    ),
    size = 2
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  theme_void() + 
  theme(
    # plot.margin = margin(-15, -50, -15, -50),
    legend.position = "inside", 
    legend.direction = "vertical",
    axis.text.y = element_text(size = 6)
  ) 
  





# library(colorspace)
# 
# n_cls <- nlevels(metabo2$`Chemical class`)
# pal <- qualitative_hcl(n_cls, palette = "Warm")
# 
# ggplot(metabo2, aes(x = as.factor(id), y = logFC, fill = `Chemical class`)) +
#   geom_bar(stat = "identity") +
#   coord_radial(start = 0, end = -0.04 * pi, expand = TRUE,
#                inner.radius = 0.55, rotate_angle = TRUE) +
#   geom_text(aes(y = label_y, label = Metabolite, angle = 90, hjust = 0), size = 2) +
#   scale_fill_manual(values = pal, drop = FALSE) +
#   theme_void() +
#   theme(legend.position = "inside", legend.direction = "vertical")

